package com.alleslocker.backend.application.auditlog.usecase

import com.alleslocker.backend.application.auditlog.dto.request.GetAllAuditLogsPagedRequestDto
import com.alleslocker.backend.application.auditlog.dto.response.GetAuditLogsPagedResponseDto
import com.alleslocker.backend.application.common.InputBoundary

interface GetAllAuditLogsPagedUseCase : InputBoundary<GetAllAuditLogsPagedRequestDto, GetAuditLogsPagedResponseDto>
