package com.alleslocker.backend.lockconnector.connectioncheck.client

import com.alleslocker.backend.domain.shared.MetadataEntry
import com.alleslocker.backend.domain.vendor.AvailableVendors
import com.alleslocker.backend.domain.vendor.VendorConnectionState
import com.alleslocker.backend.domain.vendor.VendorState
import com.alleslocker.backend.lockconnector.auth.common.TokenProvider
import com.alleslocker.backend.lockconnector.auth.config.ConfigProvider
import com.alleslocker.backend.lockconnector.common.GenericRestClient
import com.alleslocker.backend.lockconnector.connectioncheck.adapter.VendorConnectionClient
import org.springframework.http.HttpStatus
import org.springframework.http.MediaType
import org.springframework.web.client.body
import java.time.Instant

class IseoVendorConnectionClientImpl(
    private val restClient: GenericRestClient,
    private val tokenProvider: TokenProvider,
    private val configProvider: ConfigProvider,
) : VendorConnectionClient {
    override fun check(vendor: AvailableVendors): VendorState {
        val token = tokenProvider.getValidToken()
        val baseUrl = configProvider.load(vendor).baseUrl

        val response =
            restClient.getBodiless(
                endpoint = "$baseUrl/api/v2/users/me",
                headers =
                    mapOf(
                        ("Authorization" to "Bearer $token"),
                    ),
            )

        val connectionState =
            when (response.statusCode) {
                HttpStatus.OK -> VendorConnectionState.CONNECTED
                HttpStatus.FORBIDDEN -> VendorConnectionState.AUTH_FAILED
                else -> VendorConnectionState.DISCONNECTED
            }

        return VendorState(connectionState, Instant.now())
    }

    /***
     * Vendor-Data metadata field for ISEO contains credentials for an installer-account. The installer-account is needed to add new locks to the platform.
     * ***/
    override fun handleMetadata(
        vendor: AvailableVendors,
        metadata: Set<MetadataEntry>,
    ) {
        val token = tokenProvider.getValidToken()
        val baseUrl = configProvider.load(vendor).baseUrl

        val installerEmail = metadata.find { it.key == "installer-email" }?.value
        val installerPassword = metadata.find { it.key == "installer-password" }?.value

        if (installerEmail.isNullOrBlank() || installerPassword.isNullOrBlank()) {
            throw IllegalStateException(
                "Could not find installer-email or installer-password in metadata of ISEO vendor-data! This shouldn't happen because each change on MetadataEntry Set should be validated by vendorDefinitionsAdapter.validateMetadata()",
            )
        }

        val requestBody =
            mapOf(
                "username" to "alles-locker-installer",
                "firstname" to "auto",
                "lastname" to "generated by alles-locker",
                "email" to installerEmail,
                "password" to installerPassword,
                "roleIds" to listOf(2),
            )

        val response =
            restClient
                .postForResponse(
                    "$baseUrl/api/v2/users",
                    headers = mapOf(("Authorization" to "Bearer $token")),
                    body = requestBody,
                    contentType = MediaType.APPLICATION_JSON,
                ).body<IseoCreateUserResponse>()
    }

    private data class IseoCreateUserResponse(
        val id: Int,
    )
}
